CREATE TABLE IF NOT EXISTS `FULL_SYNC_TASK` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CHANNEL_ID` bigint(20) NOT NULL,
  `STATUS` varchar(20) NOT NULL,
  `STAGE` varchar(40) NOT NULL,
  `TOTAL_ROWS` bigint(20) NOT NULL DEFAULT '0',
  `COPIED_ROWS` bigint(20) NOT NULL DEFAULT '0',
  `MESSAGE` text,
  `GMT_CREATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `GMT_MODIFIED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `idx_fullSync_channel_status` (`CHANNEL_ID`,`STATUS`,`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
